### ISSUE TITLE
Failing on getInstance()

### ISSUE THREAD

**Issue by ndasim** [seratch/jslack#173]
I'm using 1.7.2 with gradle implementation, while getting instance library crashes.

`    java.lang.NoClassDefFoundError: com.github.seratch.jslack.common.http.listener.DetailedLoggingListener
        at com.github.seratch.jslack.SlackConfig.<init>(SlackConfig.java:27)
        at com.github.seratch.jslack.SlackConfig$1.<init>(SlackConfig.java:14)
        at com.github.seratch.jslack.SlackConfig.<clinit>(SlackConfig.java:14)
        at com.github.seratch.jslack.Slack.<clinit>(Slack.java:34)`

**Comment by seratch** [comment]
Can you provide more detailed information? (os, jdk version, build.grade etc)

**Comment by seratch** [comment]
Can I have more information here? Otherwise, allow me close this issue in a few days.

**Comment by seratch** [comment]
Let me close this issue. Feel free to reopen this if you revisit and see the necessity to discuss further.
