### ISSUE TITLE
Jboss Wildfly 10.0.1 NoSuchMethodException com.github.seratch.jslack.api.rtm.RTMClient.<init>()

### ISSUE THREAD

**Issue by wangdaqian08** [seratch/jslack#84]
I was using Spring annotation inject the Slack class, but the server failed to deploy and throws   

`java.lang.RuntimeException: java.lang.NoSuchMethodException: com.github.seratch.jslack.api.rtm.RTMClient.<init>()`

The full stack track of exception is:

```
01:00:50,366 INFO  [io.undertow.websockets.jsr] (ServerService Thread Pool -- 97) UT026004: Adding annotated client endpoint class com.github.seratch.jslack.api.rtm.RTMClient
01:00:50,371 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 97) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./axelerator: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./project: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85) [wildfly-undertow-10.1.0.Final.jar:10.1.0.Final]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_191]
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
	at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:101)
	at io.undertow.servlet.core.DeploymentManagerImpl.handleExtensions(DeploymentManagerImpl.java:255)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:159)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100) [wildfly-undertow-10.1.0.Final.jar:10.1.0.Final]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82) [wildfly-undertow-10.1.0.Final.jar:10.1.0.Final]
	... 6 more
Caused by: javax.websocket.DeploymentException: UT003024: Web socket deployment failed
	at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpointInternal(ServerWebSocketContainer.java:660)
	at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpoint(ServerWebSocketContainer.java:586)
	at io.undertow.websockets.jsr.Bootstrap.handleDeployment(Bootstrap.java:95)
	... 10 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.github.seratch.jslack.api.rtm.RTMClient.<init>()
	at org.jboss.as.ee.component.ReflectiveClassIntrospector.createFactory(ReflectiveClassIntrospector.java:59) [wildfly-ee-10.1.0.Final.jar:10.1.0.Final]
	at org.jboss.as.ee.component.ComponentRegistry.createInstanceFactory(ComponentRegistry.java:76) [wildfly-ee-10.1.0.Final.jar:10.1.0.Final]
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$ComponentClassIntrospector.createInstanceFactory(UndertowDeploymentInfoService.java:1444) [wildfly-undertow-10.1.0.Final.jar:10.1.0.Final]
	at io.undertow.websockets.jsr.ServerWebSocketContainer.addEndpointInternal(ServerWebSocketContainer.java:654)
	... 12 more
Caused by: java.lang.NoSuchMethodException: com.github.seratch.jslack.api.rtm.RTMClient.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) [rt.jar:1.8.0_191]
```

When I deploy the project to Jboss standalone, there is no problem, any suggestion on how to fix this problem.

- jslack: 1.1.6

- jboss/wildfly:10.1.0.Final

**Comment by seratch** [comment]
It seems to be a binary compatibility issue on WS related classes. Make sure if the loaded versions of the following dependencies in your environment.  https://github.com/seratch/jslack/blob/1.1.6/pom.xml#L70-L81

**Comment by seratch** [comment]
@wangdaqian08 Do you still have this problem? Let me know if there is something I can do for you. If I don't hear from you for a while, please allow me to close this issue sometime in the future.

**Comment by wangdaqian08** [comment]
thanks for asking @seratch, I decide no longer to use this api library, appreciate all of your time and help

**Comment by seratch** [comment]
Thank you for your response.

**Comment by Satyaki0924** [comment]
@seratch  any resolution on this? I am experiencing this same issue with jslack 1.6.0 and jboss eap7.1.6. 
@wangdaqian08 how did you solve this?
Thanks in advance.

**Comment by Satyaki0924** [comment]
For all those who is getting the same error, here is how I solved this.
**Problem**: Jboss EAP 7 websocket dependencies conflicting with jslack dependencies causing binary compatibility issue.
**Resolution**:
Add the following dependency to your POM.xml if you are using maven
```
<dependency>
<groupId>xerces</groupId>
<artifactId>xercesImpl</artifactId>
<version>2.11.0</version>
</dependency>
```
From your standalone.xml, comment the websockets part of the subsystems
```
<servlet-container name="default">
<jsp-config />
<!--websockets /-->
</servlet-container>
```
